name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Dijkstra

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build
      run: |
        dotnet publish -c Release --output build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./Dijkstra/Dijkstra/build/wwwroot
        publish_branch: gh-pages
        force_orphan: true
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
